# Generated by Django 2.1.2 on 2018-10-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('dni_repres', models.CharField(max_length=10)),
                ('nombre_repres', models.CharField(max_length=150)),
                ('tlf1', models.CharField(max_length=10)),
                ('tlf2', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('poblacion', models.CharField(max_length=30)),
                ('cp', models.CharField(max_length=5)),
                ('provincia', models.CharField(max_length=30)),
                ('iban', models.CharField(max_length=24)),
            ],
        ),
    ]
